on:
  push:
    branches:
      - master

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    name: A job to deploy canisters to the IC
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Deploy canisters
        id: deploy
        uses: anthonymq/ic-deploy-action@master
        with:
          identity: ${{ secrets.DFX_IDENTITY }}
          wallets: ${{ secrets.DFX_WALLETS }}
      - name: Push data to IC
        run: |
          echo y | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
          sudo ln -s /home/runner/bin/dfx /usr/bin/dfx

          NETWORK=ic ./initData.sh
      - name: Show success message
        run: echo success!